version: 0.2

phases:
    install:
        commands:
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - ng build --prod
            - zip -r dist.zip dist/AngSix/
    post_build:
        commands:
            - aws s3 rm s3://www.mechie.net --recursive

artifacts:
    files:
        dist/AngSix/*
    discard-paths: yes
