version: 0.2

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - ng build --prod
            - zip -r dist.zip dist/AngSix/

artifacts:
    files:
        dist.zip
