version: 0.2

phases:
    install:
        commands:
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - ng build --prod
            - zip -r dist.zip dist/AngSix/

artifacts:
    files:
        dist/AngSix/*
    discard-paths: yes
