import '@angular/platform-browser-dynamic';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/toPromise';
import 'rxjs';
import 'rxjs/Observable';
import 'ng2-webstorage';
import 'angulartics2';
import '@angular/http';
import '@angular/core';
import 'ng2-webstorage';
import '@angular/router';
import '@angular/forms';
import 'hammerjs';
import "zone.js";

import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/toPromise';